/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dao.view;
import dao.conection.mysql.Conexao;
import dao.controller.ControllerCargos;
import dao.model.CreateTableCargos;
import dao.model.CreateTableUsers;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author athena
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        Conexao iniCon =  new Conexao();
        Conexao.Conectar();
        
        CreateTableCargos create = new CreateTableCargos();
        CreateTableUsers query = new CreateTableUsers();
        initComponents();
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mnprincipal = new javax.swing.JMenuBar();
        mncadastro = new javax.swing.JMenu();
        mnicusuarios = new javax.swing.JMenuItem();
        mniccargos = new javax.swing.JMenuItem();
        mnudelete = new javax.swing.JMenu();
        mnidcargos = new javax.swing.JMenuItem();
        mnidusuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dao/view/image/lemaf27.png"))); // NOI18N

        mncadastro.setText("Cadastro");

        mnicusuarios.setText("Usuários");
        mnicusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnicusuariosActionPerformed(evt);
            }
        });
        mncadastro.add(mnicusuarios);

        mniccargos.setText("Cargos");
        mniccargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniccargosActionPerformed(evt);
            }
        });
        mncadastro.add(mniccargos);

        mnprincipal.add(mncadastro);

        mnudelete.setText("Editar/Excluir");

        mnidcargos.setText("Cargos");
        mnidcargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidcargosActionPerformed(evt);
            }
        });
        mnudelete.add(mnidcargos);

        mnidusuarios.setText("Usuários");
        mnidusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidusuariosActionPerformed(evt);
            }
        });
        mnudelete.add(mnidusuarios);

        mnprincipal.add(mnudelete);

        setJMenuBar(mnprincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniccargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniccargosActionPerformed
        CadCargos cadCargo = new CadCargos();
        cadCargo.setVisible(true);
    }//GEN-LAST:event_mniccargosActionPerformed

    private void mnicusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnicusuariosActionPerformed
        CadUsers cadUser = new CadUsers();
        cadUser.setVisible(true);
    }//GEN-LAST:event_mnicusuariosActionPerformed

    private void mnidcargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidcargosActionPerformed
        
        ShowCargos sCargos = new ShowCargos();
        sCargos.setVisible(true);
        
         
    }//GEN-LAST:event_mnidcargosActionPerformed

    private void mnidusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidusuariosActionPerformed
        ShowUsers sUsers = new ShowUsers();
        sUsers.setVisible(true);
    }//GEN-LAST:event_mnidusuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu mncadastro;
    private javax.swing.JMenuItem mniccargos;
    private javax.swing.JMenuItem mnicusuarios;
    private javax.swing.JMenuItem mnidcargos;
    private javax.swing.JMenuItem mnidusuarios;
    private javax.swing.JMenuBar mnprincipal;
    private javax.swing.JMenu mnudelete;
    // End of variables declaration//GEN-END:variables
}
