/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dao.view;

import dao.controller.ControllerCargos;
import dao.controller.ControllerUsers;
import dao.model.Users;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author athena
 */
public class ShowUsers extends javax.swing.JFrame {
    public static Users select = new Users();
    public static String nameGender = new String();
    
    /**
     * Creates new form ShowUsers
     */
    public ShowUsers() {
        initComponents();
        reboot();
        
    }
    public void reboot(){
        ControllerUsers users = new ControllerUsers();
        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
        model.setColumnCount(0);
        model.setNumRows(0);
        //ArrayList <String> entry =  cargos.SelectAll();
        model.addColumn("ID");
        model.addColumn("Nome");
        model.addColumn("CPF");
        model.addColumn("Cargo");
        model.addColumn("Nascimento");
        model.addColumn("Gênero");
        model.addColumn("Data_Cadastro");
        ArrayList <Users> user = users.selectAll();
        
        for(Users i:user) {
           String cargo = users.selectCargo(i.getCargo());
           System.out.println(cargo);
           model.insertRow(model.getRowCount(), new Object[] {i.getId(),i.getName(),i.getCpf(),users.selectCargo(i.getCargo()),i.getBorn(),i.getGender(),i.getDate_origin()});
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        bttEdit = new javax.swing.JToggleButton();
        bttDelete = new javax.swing.JToggleButton();
        bttSair = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        bttEdit.setText("Editar");
        bttEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEditActionPerformed(evt);
            }
        });

        bttDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dao/view/image/Knob Remove.png"))); // NOI18N
        bttDelete.setText("Excluir");
        bttDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttDeleteActionPerformed(evt);
            }
        });

        bttSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dao/view/image/Knob Cancel.png"))); // NOI18N
        bttSair.setText("Sair");
        bttSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSairActionPerformed(evt);
            }
        });

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dao/view/image/Knob Refresh.png"))); // NOI18N
        jToggleButton1.setText("Atualizar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bttEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bttSair, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(bttSair)
                    .addComponent(bttDelete)
                    .addComponent(bttEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEditActionPerformed
        int row = 0;
        String value = "";
        if(tblUsers.isEditing()){
            row = tblUsers.getEditingRow();
            ControllerCargos cargo = new ControllerCargos();
            nameGender = tblUsers.getModel().getValueAt(row, 3).toString();
            String idCargo = cargo.selectCode(tblUsers.getModel().getValueAt(row, 3).toString());
            this.select.setId(tblUsers.getModel().getValueAt(row, 0).toString());
            this.select.setName(tblUsers.getModel().getValueAt(row, 1).toString());
            this.select.setCpf(tblUsers.getModel().getValueAt(row, 2).toString());
            this.select.setCargo(idCargo);
            this.select.setBorn(tblUsers.getModel().getValueAt(row, 4).toString());
            this.select.setGender(tblUsers.getModel().getValueAt(row, 5).toString());
            this.select.setDate_origin(tblUsers.getModel().getValueAt(row, 6).toString());
            UpdateUsers update = new UpdateUsers();
            setDefaultCloseOperation(update.EXIT_ON_CLOSE);
            update.setVisible(true);
            reboot();
            
        }else if (tblUsers.getSelectedRow()>= row){
            row = tblUsers.getSelectedRow();
            ControllerCargos cargo = new ControllerCargos();
            String idCargo = cargo.selectCode(tblUsers.getModel().getValueAt(row, 3).toString());
            this.select.setId(tblUsers.getModel().getValueAt(row, 0).toString());
            this.select.setName(tblUsers.getModel().getValueAt(row, 1).toString());
            this.select.setCpf(tblUsers.getModel().getValueAt(row, 2).toString());
            this.select.setCargo(idCargo);
            this.select.setBorn(tblUsers.getModel().getValueAt(row, 4).toString());
            this.select.setGender(tblUsers.getModel().getValueAt(row, 5).toString());
            this.select.setDate_origin(tblUsers.getModel().getValueAt(row, 6).toString());
            UpdateUsers update = new UpdateUsers();
            update.setVisible(true);
            reboot();
        }else{
        System.out.println(tblUsers.getSelectedRow());
        reboot();
        }
        reboot();
    }//GEN-LAST:event_bttEditActionPerformed

    private void bttDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttDeleteActionPerformed
        int row = 0;
        if (tblUsers.getSelectedRow()>= row){
            ControllerUsers user = new ControllerUsers();
            System.out.println(tblUsers.getModel().getValueAt(row, 0).toString());
            row=tblUsers.getSelectedRow();
            user.delete(tblUsers.getModel().getValueAt(row, 0).toString());
            reboot();
        }
    }//GEN-LAST:event_bttDeleteActionPerformed

    private void bttSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_bttSairActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.reboot();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bttDelete;
    private javax.swing.JToggleButton bttEdit;
    private javax.swing.JButton bttSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
